### ISSUE TITLE
Uf Fehler reagiere

### ISSUE THREAD

**Issue by thde** [thde/CarRenter3000#24]
Uf Fehler reagiere isch vorallem, I'm gui dialog sende und de Fehler melde wenn eppis ned stimmt

**Comment by chaenni** [comment]
TODOs aluege

**Comment by chaenni** [comment]
Message Box anzeigen

**Comment by lroellin** [comment]
Die andere händ irgendwo sones Fehlerfeld glaub. Aber da chasch di lang drüber striite, MessageBox isch sicher mal besser als eifach nüt

**Comment by lroellin** [comment]
Done (#39)
